import type { ImportConfig } from "../types";

export const expenseImportConfig: ImportConfig = {
  entityName: "expenses",
  entityLabel: "Expenses",
  entityLabelSingular: "Expense",
  tableName: "expenses",
  templateFileName: "expenses_import_template.csv",
  columns: [
    {
      key: "amount",
      label: "Amount",
      required: true,
      type: "number",
      aliases: ["cost", "price", "total"],
    },
    {
      key: "date",
      label: "Date",
      required: true,
      type: "date",
      aliases: ["expense_date", "purchase_date"],
    },
    {
      key: "category",
      label: "Category",
      required: true,
      type: "fk_lookup",
      fkTable: "expense_categories",
      fkDisplayField: "name",
      fkIdField: "name",
      aliases: ["expense_category", "type"],
    },
    {
      key: "vendor",
      label: "Vendor",
      required: false,
      type: "string",
      aliases: ["merchant", "store", "supplier", "payee"],
    },
    {
      key: "description",
      label: "Description",
      required: false,
      type: "string",
      aliases: ["notes", "details", "memo"],
    },
    {
      key: "payment_method",
      label: "Payment Method",
      required: false,
      type: "enum",
      enumValues: [
        "bank_transfer",
        "cash",
        "check",
        "paypal",
        "gcash",
        "maya",
        "wise",
        "other",
      ],
      aliases: ["payment", "method", "paid_with"],
    },
    {
      key: "is_tax_deductible",
      label: "Tax Deductible",
      required: false,
      type: "boolean",
      defaultValue: true,
      aliases: ["deductible", "tax_deductible"],
    },
    {
      key: "project_id",
      label: "Project",
      required: false,
      type: "fk_lookup",
      fkTable: "projects",
      fkDisplayField: "name",
      fkIdField: "id",
      aliases: ["project", "project_name"],
    },
  ],
};
