import type { ImportConfig } from "../types";

export const projectImportConfig: ImportConfig = {
  entityName: "projects",
  entityLabel: "Projects",
  entityLabelSingular: "Project",
  tableName: "projects",
  templateFileName: "projects_import_template.csv",
  columns: [
    {
      key: "name",
      label: "Project Name",
      required: true,
      type: "string",
      aliases: ["project", "title", "project_name"],
    },
    {
      key: "client_id",
      label: "Client",
      required: false,
      type: "fk_lookup",
      fkTable: "clients",
      fkDisplayField: "company_name",
      fkIdField: "id",
      aliases: ["client", "company", "company_name"],
    },
    {
      key: "type",
      label: "Type",
      required: false,
      type: "enum",
      enumValues: ["fixed", "hourly", "retainer"],
      defaultValue: "hourly",
      aliases: ["project_type", "billing_type"],
    },
    {
      key: "rate",
      label: "Rate",
      required: false,
      type: "number",
      aliases: ["hourly_rate", "price"],
    },
    {
      key: "estimated_hours",
      label: "Estimated Hours",
      required: false,
      type: "number",
      aliases: ["hours_estimate", "budget_hours"],
    },
    {
      key: "deadline",
      label: "Deadline",
      required: false,
      type: "date",
      aliases: ["due_date", "end_date"],
    },
    {
      key: "status",
      label: "Status",
      required: false,
      type: "enum",
      enumValues: [
        "not_started",
        "in_progress",
        "on_hold",
        "completed",
        "cancelled",
      ],
      defaultValue: "not_started",
      aliases: ["project_status"],
    },
    {
      key: "description",
      label: "Description",
      required: false,
      type: "string",
      aliases: ["desc", "details"],
    },
  ],
};
